<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Giao diện</div><h2 class="page-title">Quản lý menu</h2><div class="text-secondary mt-1">Tạo menu nhiều cấp cho từng vị trí trên website.</div></div><div class="col-auto ms-auto"><button type="button" class="btn btn-primary" data-entity-create data-title="Thêm menu"><?php echo admin_icon('plus'); ?> Thêm menu</button></div></div></div></div>
<div class="page-body"><div class="container-xl"><div class="card">
	<div class="card-header"><div class="btn-list"><span class="text-secondary align-self-center">Vị trí:</span><?php foreach ($locations as $key => $label): ?><a class="btn <?php echo $location === $key ? 'btn-primary' : 'btn-outline-secondary'; ?>" href="<?php echo site_url('admin/menu') . '?location=' . rawurlencode($key); ?>"><?php echo html_escape($label); ?></a><?php endforeach; ?></div></div>
	<?php if (empty($items)): ?><div class="empty"><div class="empty-icon"><?php echo admin_icon('menu', 'icon icon-lg'); ?></div><p class="empty-title">Chưa có mục menu</p><p class="empty-subtitle">Tạo mục đầu tiên cho <?php echo html_escape($locations[$location]); ?>.</p></div><?php else: ?><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Tên menu</th><th>Đường dẫn</th><th>Trạng thái</th><th class="text-center">Thứ tự</th><th class="w-1"></th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><div style="padding-left: <?php echo (int) $item['depth'] * 24; ?>px"><span class="fw-medium"><?php echo html_escape($item['title']); ?></span><?php if ((int) $item['child_count'] > 0): ?> <span class="badge bg-blue-lt"><?php echo (int) $item['child_count']; ?> con</span><?php endif; ?></div></td><td class="text-secondary text-truncate" style="max-width: 260px"><?php echo html_escape($item['url']); ?><?php echo $item['target'] === '_blank' ? ' · tab mới' : ''; ?></td><td><?php echo (int) $item['status'] === 1 ? '<span class="status status-green"><span class="status-dot"></span>Hiển thị</span>' : '<span class="status status-secondary"><span class="status-dot"></span>Đang ẩn</span>'; ?></td><td class="text-center text-secondary"><?php echo (int) $item['sort_order']; ?></td><td><div class="btn-list flex-nowrap justify-content-end"><form method="post" action="<?php echo site_url('admin/menu/doi-thu-tu/' . $item['id'] . '/up'); ?>"><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?><button class="btn btn-sm btn-icon btn-ghost-secondary" title="Lên" aria-label="Đưa lên"<?php echo $item['is_first'] ? ' disabled' : ''; ?>>↑</button></form><form method="post" action="<?php echo site_url('admin/menu/doi-thu-tu/' . $item['id'] . '/down'); ?>"><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?><button class="btn btn-sm btn-icon btn-ghost-secondary" title="Xuống" aria-label="Đưa xuống"<?php echo $item['is_last'] ? ' disabled' : ''; ?>>↓</button></form><button type="button" class="btn btn-sm btn-icon btn-ghost-primary" title="Sửa" aria-label="Sửa menu" data-entity-edit="<?php echo site_url('admin/menu/chi-tiet/' . $item['id']); ?>" data-title="Sửa menu"><?php echo admin_icon('edit'); ?></button><button type="button" class="btn btn-sm btn-icon btn-ghost-danger" title="Xóa" aria-label="Xóa menu" data-confirm-url="<?php echo site_url('admin/menu/xoa/' . $item['id']); ?>" data-confirm-text="Xóa mục menu &quot;<?php echo html_escape($item['title']); ?>&quot;? Menu có menu con sẽ không thể xóa."><?php echo admin_icon('trash'); ?></button></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></div></div>
<script>
document.addEventListener('DOMContentLoaded', function () {
	var title = document.querySelector('#entity-modal [name="title"]');
	if (!title || document.querySelector('#entity-modal [name="title_en"]')) return;
	title.parentElement.className = 'col-md-6';
	var field = document.createElement('div');
	field.className = 'col-md-6';
	field.innerHTML = '<label class="form-label" for="menu-title-en">Tên menu tiếng Anh</label><input class="form-control" id="menu-title-en" name="title_en" maxlength="150" placeholder="Để trống sẽ dùng tên tiếng Việt"><div class="invalid-feedback" data-error-for="title_en"></div>';
	title.parentElement.insertAdjacentElement('afterend', field);
});
</script>
<div class="modal modal-blur fade" id="entity-modal" tabindex="-1" aria-hidden="true" data-entity-modal data-bs-backdrop="static"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content" method="post" action="<?php echo site_url('admin/menu/luu'); ?>" novalidate><input type="hidden" name="id" value=""><input type="hidden" name="location" value="<?php echo html_escape($location); ?>"><div class="modal-header"><h5 class="modal-title" data-modal-title>Thêm menu</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label required" for="menu-title">Tên menu</label><input class="form-control" id="menu-title" name="title" maxlength="150" required><div class="invalid-feedback" data-error-for="title"></div></div><div class="col-md-4"><label class="form-label" for="menu-order">Thứ tự</label><input class="form-control" id="menu-order" name="sort_order" type="number" min="0" value="0"><div class="invalid-feedback" data-error-for="sort_order"></div></div><div class="col-md-8"><label class="form-label required" for="menu-url">Đường dẫn</label><input class="form-control" id="menu-url" name="url" maxlength="255" placeholder="/tin-tuc hoặc https://…" required><div class="invalid-feedback" data-error-for="url"></div></div><div class="col-md-4"><label class="form-label" for="menu-parent">Menu cha</label><select class="form-select" id="menu-parent" name="parent_id"><option value="">Không có, ở cấp cao nhất</option><?php foreach ($parentOptions as $parent): ?><option value="<?php echo (int) $parent['id']; ?>"><?php echo str_repeat('— ', (int) $parent['depth']); ?><?php echo html_escape($parent['title']); ?></option><?php endforeach; ?></select><div class="invalid-feedback" data-error-for="parent_id"></div></div><div class="col-md-6"><label class="form-label" for="menu-target">Cách mở liên kết</label><select class="form-select" id="menu-target" name="target"><option value="_self">Cùng tab</option><option value="_blank">Tab mới</option></select></div><div class="col-md-6 d-flex align-items-end"><label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="status" value="1" checked><span class="form-check-label">Hiển thị menu</span></label></div></div></div><div class="modal-footer"><button type="button" class="btn btn-link link-secondary" data-bs-dismiss="modal">Hủy</button><button type="submit" class="btn btn-primary ms-auto">Lưu</button></div></form></div></div>
